version: '3.0'

services:
  frontend:
    build: .
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3001"
    stdin_open: true 
    tty: true